//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Code generated by ScreenMaker - Internal version 22.1.9826.0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.13.4007")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("22.1.9826.0")]
[assembly: ABB.Robotics.Tps.Taf.TpsViewAttribute("FCV", "tpu-Operator32.png", "tpu-Operator32.png", "TpsViewScreenMaker_1.dll", "ScreenMaker_1.MainScreen", ABB.Robotics.Tps.Taf.StartPanelLocation.Left, ABB.Robotics.Tps.Taf.TpsViewType.Static, ABB.Robotics.Tps.Taf.TpsViewStartupTypes.Manual)]


